#!/home/ec2-user/apps/kanji/backend/venv/bin/python3
"""
add_ru_aliases.py — attach a Russian-language alias to every kanji/hanzi row
whose English keyword we have a translation for (owner-requested, 2026-09-01:
"перевести названия каждого иероглифа по хейсигу на русский и добавить как
алиас" — translate each kanji's Heisig name into Russian and add it as an
alias, so a Russian-speaking user can search by the Russian word too. Extended
2026-09-20 per the owner: cover every kanji/hanzi/primitive, not just the
pilot batch — "не надо думать", i.e. bulk machine translation is fine here,
this isn't meant to be a hand-verified pass like the decomposition audits).

## Why a separate pseudo-account, not owner_id=1

These aliases are machine-translated, not part of Heisig's book or the CSV/
data.txt source files — attaching them to the reserved system account
(owner_id=1) would make them indistinguishable from real Heisig data. Instead
this script creates (idempotently) a dedicated account, 'ru-aliases', with no
password (auth_provider='system', same pattern the reserved system account
itself uses) so nobody can log in as it — it's edited only by re-running this
script, matching the 'ai-mnemonics' pseudo-account CLAUDE.md already queues
for bulk LLM-generated mnemonics, applied here to bulk LLM-generated
translations instead. Its aliases are public by default (visibility='public')
so any anonymous visitor benefits from them immediately.

## Matching strategy

Matches by *keyword text*, not by id or script, against every public,
system-owned (owner_id=1) kanji/hanzi row — so translating one English word
("one") automatically covers every row that happens to share that exact
keyword, ja-kanji and every zh-* script alike (e.g. rtk1/一, hanzi-4e00/一,
and rarer synonyms like hanzi-5e7a/幺 which CSV/Unihan also gloss "one").
This is deliberate: Heisig's RTK keyword and a hanzi's Unihan-derived English
gloss are both just English labels for a meaning, and a correct Russian
translation of that meaning is correct for any row carrying it, regardless of
which pipeline (import_data vs import_hanzi) originally created the row.

TRANSLATIONS below is a small, hand-verified pilot batch (RTK frames 1-100) —
see docs/2026-08-search-quality-audit.md for why that pilot started small.
Everything else (of the ~18,800 unique keywords across ~24,200 public
kanji/hanzi/primitive rows) is covered by `ru_translations_auto.json`, a
flat {keyword: translation} cache generated by argos-translate (offline,
free, no API key — see --refresh-translations below), checked into git
next to this script the same way google_decompositions.json/google_doubts.json
already cache other expensive external lookups. TRANSLATIONS always wins on
overlap: a hand-checked entry is never overridden by the bulk MT cache. This
is deliberately not hand-verified at this scale (owner: "не надо думать") —
expect the occasional odd or context-blind translation (short, jargon-y
Heisig keywords like "sickness radical" or transliterated non-English
keywords like "kwukyel" translate worse than plain nouns); an alias is
low-stakes to get wrong compared to decomposition data, and a bad one is
just as easy to fix by adding an override to TRANSLATIONS as the pilot
batch's entries were.

Usage:
    python3 add_ru_aliases.py [--dry-run] [--limit N]
    python3 add_ru_aliases.py --refresh-translations   # needs `pip install argostranslate`
                                                         # (not in requirements.txt — heavy,
                                                         # only needed to add new keywords)

Safe to re-run: every alias insert is INSERT OR IGNORE against the
UNIQUE(kanji_id, alias, owner_id) constraint, so a repeat run with an
unchanged translation set adds nothing new.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import database  # noqa: E402

RU_ALIASES_USERNAME = "ru-aliases"
RU_ALIASES_DISPLAY_NAME = "Russian Aliases (auto-translated)"

# English keyword (lowercase, exact match against kanji.keyword) -> Russian
# translation. Pilot batch: RTK frames 1-100. Each was translated by hand
# against the real keyword text pulled from a live-imported DB, not guessed
# from memory of what frame N "usually" is -- see the audit doc entry for
# spot-check notes on the handful of non-obvious ones (旬/"decameron" ->
# "декада", since Heisig's keyword is itself a wordplay on a 10-day period;
# 中/"in" -> "внутри" rather than the bare preposition "в", closer to how
# 中 is actually used as a primitive meaning "inside/within").
TRANSLATIONS = {
    "one": "один",
    "two": "два",
    "three": "три",
    "four": "четыре",
    "five": "пять",
    "six": "шесть",
    "seven": "семь",
    "eight": "восемь",
    "nine": "девять",
    "ten": "десять",
    "mouth": "рот",
    "day": "день",
    "month": "месяц",
    "rice field": "рисовое поле",
    "eye": "глаз",
    "old": "старый",
    "i": "я",
    "risk": "риск",
    "companion": "товарищ",
    "bright": "яркий",
    "chant": "распевать",
    "sparkle": "сверкание",
    "goods": "товары",
    "spine": "хребет",
    "prosperous": "процветающий",
    "early": "ранний",
    "rising sun": "восходящее солнце",
    "generation": "поколение",
    "stomach": "желудок",
    "nightbreak": "рассвет",
    "gall bladder": "жёлчный пузырь",
    "span": "промежуток",
    "concave": "вогнутый",
    "convex": "выпуклый",
    "olden times": "старые времена",
    "oneself": "сам",
    "white": "белый",
    "hundred": "сто",
    "in": "внутри",
    "thousand": "тысяча",
    "tongue": "язык",
    "measuring box": "мерная коробка",
    "rise up": "подниматься",
    "round": "круглый",
    "measurement": "мера",
    "elbow": "локоть",
    "specialty": "специальность",
    "dr.": "доктор",
    "fortune-telling": "гадание",
    "above": "сверху",
    "below": "снизу",
    "eminent": "выдающийся",
    "morning": "утро",
    "derision": "насмешка",
    "only": "только",
    "shellfish": "ракушка",
    "pop song": "песня",
    "upright": "честный",
    "employee": "служащий",
    "post a bill": "расклеивать афиши",
    "see": "видеть",
    "newborn babe": "младенец",
    "beginning": "начало",
    "page": "страница",
    "stubborn": "упрямый",
    "mediocre": "посредственный",
    "ten thousand": "десять тысяч",
    "phrase": "фраза",
    "texture": "текстура",
    "decameron": "декада",
    "ladle": "половник",
    "bull's eye": "мишень",
    "neck": "шея",
    "fish guts": "рыбьи потроха",
    "riot": "бунт",
    "straightaway": "прямо",
    "tool": "инструмент",
    "true": "истинный",
    "craft": "ремесло",
    "left": "левый",
    "right": "правый",
    "possess": "обладать",
    "defeat": "поражение",
    "bribe": "взятка",
    "tribute": "дань",
    "paragraph": "абзац",
    "sword": "меч",
    "blade": "лезвие",
    "cut": "резать",
    "seduce": "соблазнять",
    "shining": "сияющий",
    "rule": "правило",
    "vice-": "вице-",
    "separate": "отдельный",
    "street": "улица",
    "village": "деревня",
    "can": "мочь",
    "place on the head": "класть на голову",
    "child": "ребёнок",
    "cavity": "полость",
    "tree": "дерево",
    "a catty (approximately 600 g)": "цзинь (примерно 600 г)",
    # Spot-fixed after the 2026-09-20 bulk auto-translation pass: argos-translate
    # gave the adjective "горный" (mountainous) for this common, high-traffic
    # primitive instead of the noun a learner would actually type.
    "mountain": "гора",
}


AUTO_CACHE_PATH = Path(__file__).parent / "ru_translations_auto.json"

# SQLite's default max bound-variable count (SQLITE_MAX_VARIABLE_NUMBER) can be as
# low as 999 depending on build, and the merged translation set runs into the tens
# of thousands -- chunk any IN (...) query against it rather than assuming one query
# can hold them all.
_QUERY_CHUNK = 500


def load_all_translations() -> dict[str, str]:
    """Pilot dict (hand-verified) merged over the bulk auto-translated cache --
    TRANSLATIONS always wins on a shared key."""
    auto = {}
    if AUTO_CACHE_PATH.exists():
        auto = json.loads(AUTO_CACHE_PATH.read_text(encoding="utf-8"))
    return {**auto, **TRANSLATIONS}


def refresh_translations(conn) -> None:
    """Bulk-translate every public system keyword not already covered (by the pilot
    dict or the existing cache) via argos-translate, an offline EN->RU model -- no
    API key, no per-request network rate limit, safe to re-run as new keywords show
    up (e.g. after import_hanzi.py or a data.txt addition). Writes incrementally so
    an interrupted run loses at most the last _QUERY_CHUNK-ish translations."""
    import argostranslate.package
    import argostranslate.translate

    installed = {p.to_code for p in argostranslate.package.get_installed_packages()
                 if p.from_code == "en"}
    if "ru" not in installed:
        print("Downloading the en->ru argos-translate model (one-time)...")
        argostranslate.package.update_package_index()
        pkg = next(p for p in argostranslate.package.get_available_packages()
                   if p.from_code == "en" and p.to_code == "ru")
        argostranslate.package.install_from_path(pkg.download())

    rows = conn.execute(
        "SELECT DISTINCT keyword FROM kanji WHERE owner_id = 1 AND visibility = 'public' "
        "AND keyword IS NOT NULL AND keyword != '' ORDER BY keyword"
    ).fetchall()
    all_keywords = [r["keyword"] for r in rows]

    cache = json.loads(AUTO_CACHE_PATH.read_text(encoding="utf-8")) if AUTO_CACHE_PATH.exists() else {}
    todo = [k for k in all_keywords if k not in TRANSLATIONS and k not in cache]
    print(f"{len(all_keywords)} total unique keywords, {len(todo)} need translating "
          f"({len(TRANSLATIONS)} in the pilot dict, {len(cache)} already cached)")

    for i, kw in enumerate(todo):
        cache[kw] = argostranslate.translate.translate(kw, "en", "ru")
        if i % 200 == 0:
            AUTO_CACHE_PATH.write_text(
                json.dumps(cache, ensure_ascii=False, indent=1, sort_keys=True), encoding="utf-8")
            print(f"  {i}/{len(todo)}  {kw!r} -> {cache[kw]!r}")

    AUTO_CACHE_PATH.write_text(
        json.dumps(cache, ensure_ascii=False, indent=1, sort_keys=True), encoding="utf-8")
    print(f"done, {len(cache)} translations cached in {AUTO_CACHE_PATH.name}")


def ensure_ru_aliases_account(conn) -> int:
    conn.execute(
        "INSERT OR IGNORE INTO users (username, auth_provider, display_name) "
        "VALUES (?, 'system', ?)",
        (RU_ALIASES_USERNAME, RU_ALIASES_DISPLAY_NAME),
    )
    conn.commit()
    row = conn.execute(
        "SELECT id FROM users WHERE username = ?", (RU_ALIASES_USERNAME,)
    ).fetchone()
    return row["id"]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit", type=int, default=None,
                         help="only process the first N matching rows (by id)")
    parser.add_argument("--refresh-translations", action="store_true",
                         help="bulk-translate any new keywords via argos-translate, then exit")
    args = parser.parse_args()

    conn = database.get_db()

    if args.refresh_translations:
        refresh_translations(conn)
        return

    owner_id = ensure_ru_aliases_account(conn)
    print(f"ru-aliases account id={owner_id}")

    translations = load_all_translations()
    keywords = list(translations.keys())

    rows = []
    for i in range(0, len(keywords), _QUERY_CHUNK):
        chunk = keywords[i:i + _QUERY_CHUNK]
        placeholders = ",".join("?" * len(chunk))
        rows.extend(conn.execute(
            f"SELECT id, character, keyword, script FROM kanji "
            f"WHERE owner_id = 1 AND visibility = 'public' AND keyword IN ({placeholders}) "
            f"ORDER BY id",
            chunk,
        ).fetchall())

    if args.limit:
        rows = rows[: args.limit]

    inserted = 0
    skipped_existing = 0
    skipped_empty = 0
    replaced_stale = 0
    for row in rows:
        # _insert_alias() always does alias.strip().lower() before storing/comparing,
        # so match that here too -- otherwise a capitalized MT translation looks
        # "not yet present" forever even after its lowered form was already inserted.
        ru = translations[row["keyword"]].strip().lower()
        if not ru:
            # argos-translate returns "" for input it can't handle at all (mostly
            # obscure hanzi whose own "keyword" is a raw CJK character, not English,
            # because Unihan had no kDefinition gloss for it) -- _insert_alias()
            # would silently no-op on this anyway, but skip it here too so the
            # reported count reflects what actually landed in the aliases table.
            skipped_empty += 1
            continue
        stale = conn.execute(
            "SELECT COUNT(*) FROM aliases WHERE kanji_id = ? AND owner_id = ? AND alias != ?",
            (row["id"], owner_id, ru),
        ).fetchone()[0]
        if stale and not args.dry_run:
            conn.execute(
                "DELETE FROM aliases WHERE kanji_id = ? AND owner_id = ? AND alias != ?",
                (row["id"], owner_id, ru),
            )
        replaced_stale += stale
        existing = conn.execute(
            "SELECT 1 FROM aliases WHERE kanji_id = ? AND alias = ? AND owner_id = ?",
            (row["id"], ru, owner_id),
        ).fetchone()
        if existing:
            skipped_existing += 1
            continue
        print(f"  {row['id']} {row['character']} ({row['keyword']}) -> {ru}")
        if not args.dry_run:
            database.create_alias(conn, row["id"], owner_id, ru, "public")
        inserted += 1

        print(f"\n{'Would insert' if args.dry_run else 'Inserted'} {inserted} alias(es), "
            f"{replaced_stale} stale alias(es) replaced, {skipped_existing} already present, "
            f"{skipped_empty} skipped (no usable "
          f"translation). {len(rows)} row(s) matched {len(translations)} translated "
          f"keyword(s).")


if __name__ == "__main__":
    main()
